import {
  breakpoints,
  dark,
  light,
  motion,
  palette,
  radius,
  shadow,
  typography,
  type SemanticColors,
} from './tokens.js';

function paletteVariables(): string[] {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(palette)) {
    if (typeof value === 'string') {
      lines.push(`  --color-${name}: ${value};`);
      continue;
    }
    for (const [shade, hex] of Object.entries(value)) {
      lines.push(`  --color-${name}-${shade}: ${hex};`);
    }
  }
  return lines;
}

function semanticBlock(selector: string, colors: SemanticColors, indent = ''): string {
  const body = Object.entries(colors)
    .map(([name, value]) => `${indent}  --rc-${name}: ${value};`)
    .join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

/** Tailwind CSS v4 stylesheet with the brand theme and light and dark semantic colors. */
export function buildCss(): string {
  const theme = [
    ...paletteVariables(),
    `  --font-display: ${typography.display};`,
    `  --font-sans: ${typography.body};`,
    ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${v};`),
    ...Object.entries(shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
    ...Object.entries(breakpoints).map(([k, v]) => `  --breakpoint-${k}: ${v / 16}rem;`),
    `  --ease-brand: ${motion.ease};`,
    `  --duration-fast: ${motion.fast};`,
    `  --duration-base: ${motion.base};`,
    `  --duration-slow: ${motion.slow};`,
  ].join('\n');
  const semanticTheme = Object.keys(light)
    .map((name) => `  --color-${name}: var(--rc-${name});`)
    .join('\n');
  return [
    '/* Generated by @rc/design-tokens. Do not edit. */',
    `@theme {\n${theme}\n}`,
    `@theme inline {\n${semanticTheme}\n}`,
    semanticBlock(':root', light),
    `@media (prefers-color-scheme: dark) {\n${semanticBlock(':root:not([data-theme="light"])', dark, '  ')}\n}`,
    semanticBlock(':root[data-theme="dark"]', dark),
    ':root { color-scheme: light; }',
    ':root[data-theme="dark"] { color-scheme: dark; }',
    '',
  ].join('\n\n');
}
