name: refrigeracao-castro

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: castro
      POSTGRES_PASSWORD: castro
      POSTGRES_DB: castro
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U castro']
      interval: 2s
      timeout: 3s
      retries: 30

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    healthcheck:
      test: ['CMD', '/mailpit', 'readyz']
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  postgres-data:
