# Retorna todos os produtos
GET http://localhost:3000/products/
Content-Type: application/json
###

# Retorna todos os produtos com categoria 1
GET http://localhost:3000/products/?categoryid=1
Content-Type: application/json
###

# Retorna todos os produtos com categoria 1 e nome geladeira
GET http://localhost:3000/products/?categoryid=1&name=geladeira
Content-Type: application/json
###

# Retorna detalhes de um produto
GET http://localhost:3000/products/1
Content-Type: application/json
###

# Insere um produto geladeira
POST http://localhost:3000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NjM1MzkwLCJleHAiOjE2Njg2Mzg5OTB9.O_cFneEk2LAQnJRoboQTcGuZWG_4vsmXxh_VFk4cKgc

{
    "name" : "Geladeira Brastemp",
    "price" : 850.00,
    "description": "Geladeira em excelentes condições, branca, semi nova, único dono, recém reformada.",
    "state" : "Usada",
    "categoryid" : 1,
    "quantity" : 10
}
###

# Altera quantidade de geladeira para 10
PATCH http://localhost:3000/products/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4Nzk5NzIzLCJleHAiOjE2Njg4MDMzMjN9.kQAVMVEdUPOOJ6ahP16EAjRQgCrSSZoV_UBWDpYboWM

{
    "name" : "Geladeira Brastemp",
    "price" : 850.00,
    "description": "Geladeira em excelentes condições, branca, semi nova, único dono, recém reformada.",
    "state" : "Usada",
    "quantity" : 10
}
###

# Insere um produto ar condicionado
POST http://localhost:3000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NjQwMjQwLCJleHAiOjE2Njg2NDM4NDB9.-yGPO-vWRAyPqcUnDRqQU9ijVGT9F1m9IHeYzecrJy8

{
    "name" : "Ar condicionado Spring Carrier",
    "price" : 1100.00,
    "description": "Ar condicionado novo, cromado, 9000 btus.",
    "state" : "Novo",
    "categoryid" : 2,
    "quantity" : 3
}
###

# Altera quantidade de ar condicionado para 3
PATCH http://localhost:3000/products/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4Nzk5NzIzLCJleHAiOjE2Njg4MDMzMjN9.kQAVMVEdUPOOJ6ahP16EAjRQgCrSSZoV_UBWDpYboWM

{
    "name" : "Ar condicionado Spring Carrier",
    "price" : 1100.00,
    "description": "Ar condicionado novo, cromado, 9000 btus.",
    "state" : "Novo",
    "quantity" : 3
}
###

# Altera um produto
PATCH http://localhost:3000/products/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIiwiY3BmIjoiMTIzMTIzMTIzMTIiLCJyb2xlIjoyLCJpYXQiOjE2NTU0ODk1MTgsImV4cCI6MTY1NTQ5MzExOH0.bj-jNz0nPQdGVQa5n_roeCdvFi0EhxCV0KdV2RiZBso

{
    "name" : "Geladeira Consul",
    "price" : 720.37,
    "description": "Geladeira moderna, blindex, semi nova, econômica, com peças novas trocadas.",
    "state" : "Usada"
}
###

# Remove um produto
DELETE http://localhost:3000/products/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs
###

# Retorna todas as imagens da geladeira
GET http://localhost:3000/products/2/image
Content-Type: application/json
###

# Insere uma imagem
POST http://localhost:3000/products/2/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzI1NjYwLCJleHAiOjE2Njg3MjkyNjB9.2nwE1qVp4aHEM0-DPruCtXSDLppBrUUiRjivMGT8TXE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="geladeira.jpg"
Content-Type: image/jpeg

< ../../imagens/geladeira.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# Remove uma imagem
DELETE http://localhost:3000/products/2/image/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4ODAwMjQyLCJleHAiOjE2Njg4MDM4NDJ9.UEfRdCgdLD2Jb6s01N07hHWEYlT9yVraEcrGg_IV_7w
###
