# Cadastra um Gerente
POST http://localhost:3000/users/manager
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs

{
    "cpf" : "12312312312",
    "name": "Gerente de Teste",
    "email" : "gerente@gmail.com",
    "phone" : "19998877665",
    "address" : "Rua Das Couves 151, Apartamento 123, Bloco A",
    "city" : "Mogi Mirim",
    "password" : "123123"
}

###

# Cadastra um Colaborador
POST http://localhost:3000/users/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs

{
    "cpf" : "98798798798",
    "name": "Colaborador de Teste",
    "email" : "colaborador@gmail.com",
    "phone" : "19976543211",
    "address" : "Rua Dos Repolhos 1054",
    "city" : "Mogi Mirim",
    "password" : "123456"
}

###

# Cadastra um Cliente
POST http://localhost:3000/users
Content-Type: application/json

{
    "cpf" : "32132132132",
    "name": "Cliente de Teste",
    "email" : "cliente@gmail.com",
    "phone" : "19112233445",
    "address" : "Rua Dos Alfaces 867, Apartamento 200, Bloco D",
    "city" : "Mogi Mirim",
    "password" : "321321"
}

###

# Faz o login do super usuário
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "superusuario@gmail.com",
    "password" : "super"
}

###

# Faz o login do gerente
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "gerente@gmail.com",
    "password" : "123123"
}

###

# Faz o login do colaborador
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "colaborador@gmail.com",
    "password" : "123456"
}

###

# Faz o login do cliente
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "cliente@gmail.com",
    "password" : "321321"
}

###

# Atualiza os dados do cliente
PATCH http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoiY2xpZW50ZUBnbWFpbC5jb20iLCJjcGYiOiIzMjEzMjEzMjEzMiIsInJvbGUiOjQsImlhdCI6MTY2OTY2ODQ5NiwiZXhwIjoxNjY5NjcyMDk2fQ.U0hYTvBeT7ol_QUWXYuIQMjQ_ick7xY1BrXzWCPTusA

{
    "name": "Cliente de Teste Atualizado",
    "email" : "clienteatualizado@gmail.com",
    "phone" : "19002233445",
    "address" : "Rua Atualizada 867, Apartamento 200, Bloco D",
    "city" : "Mogi Mirim Atualizado"
}
###

# Obtém todos os clientes
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4ODk3NTI4LCJleHAiOjE2Njg5MDExMjh9.GI8Tk5jcJllR-wnTrEn0lvcWeGD03mv3RH8vv8YFAkQ

###

# Obtém detalhes do cliente 1
GET http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoiY2xpZW50ZUBnbWFpbC5jb20iLCJjcGYiOiIzMjEzMjEzMjEzMiIsInJvbGUiOjQsImlhdCI6MTY2OTY2ODQ5NiwiZXhwIjoxNjY5NjcyMDk2fQ.U0hYTvBeT7ol_QUWXYuIQMjQ_ick7xY1BrXzWCPTusA
###

# Deleta um cliente
DELETE http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs

{
    "cpf" : "32132132132",
    "email" : "cliente@gmail.com"
}

###

# Deleta um colaborador
DELETE http://localhost:3000/users/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs

{
    "email" : "apagar@gmail.com",
    "cpf" : "11122211122"
}

###

# Deleta um gerente
DELETE http://localhost:3000/users/manager
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic3VwZXJ1c3VhcmlvQGdtYWlsLmNvbSIsImNwZiI6IjExMTIyMjMzMzQ1Iiwicm9sZSI6MSwiaWF0IjoxNjY4NzA5NzQ5LCJleHAiOjE2Njg3MTMzNDl9.lZQdKqp5cZJh4Nh5SDkwqaDC8eZeaVEpy2p-WBUtXRs

{
    "email" : "apagar@gmail.com",
    "cpf" : "11122211122"
}

###
